version: '2.3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: wardrober
      POSTGRES_DB: wardrober
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 5
  backend:
    build: .
    network_mode: host
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy